### PR TITLE
Fix FrameStrategy

### PR DESCRIPTION
**Pull request by khandieyea**
FrameStrategy was passed a payload and returns an array of frames which breaks other strategies below it.

### CODE REVIEW

**Comment by ArturMoczulski** [comment]
@khandieyea can you sync with latest changes in `master`? So the Travis CI builds pass and we can merge.

**Comment by zoltanpeto** [comment]
This causes problems to us too, any chance this fix could be released ASAP?

**Comment by khandieyea** [comment]
@ArturMoczulski  It passes now :grin:  Press that big shiny green button...you know you want to :tada:

**Comment by vitxd** [comment]
Hello,
when can we expect this to be part of a new tag?

**Comment by ArturMoczulski** [comment]
@vitxd I will be releasing the new PHP tag probably this weekend.

**Comment by vitxd** [comment]
@ArturMoczulski thank you very much!

**Pull request merged**
