### PR TITLE
GitHub Issue #127: Add the request body to the item payload

### PR DESCRIPTION
**Pull request by ArturMoczulski**
This PR covers #127 

Added raw request body to the payload. This should be automatically scrubbed with changes coming from https://github.com/rollbar/rollbar-php/pull/126

### CODE REVIEW

**Comment by ArturMoczulski** [comment]
This PR is failing to build in Travis due to a bug in tests/DataBuilderTest.php no related to the issue. The bug is fixed in https://github.com/rollbar/rollbar-php/pull/126 PHPUnit will be passing once both PRs come together.

**Comment by rokob** [comment]
This looks good, can you rebase on master now that #126 has been merged just so we can be sure the tests pass.

**Comment by rokob** [comment]
Is there some way we can ignore those style warnings in the mock?

**Comment by rokob** [comment]
Failure on hhvm only? That looks suspicious.

**Comment by ArturMoczulski** [comment]
Yeah, I'm looking into it. Started setting up hhvm on my dev environment last night.

**Comment by ArturMoczulski** [comment]
I'm still not exactly sure what's the convention for providing the level for log method. Some places use \Rollbar\Payload\Level::fromName() others the PHPUnit's LogLevel. However, both are static calls (to a method or a constant). Not sure how we would change this to not use static calls in this case.

**Comment by ArturMoczulski** [comment]
This is ready for merge. HHVM is passing now.

**Comment by rokob** [comment]
🚀

**Pull request merged**
