### PR TITLE
Configurable Exception Raising for rollbar.log

### LINKED ISSUE #448: Re-raise exceptions in test and development environments based on a config option
A commonly requested feature is being able to re-raise exceptions in test and development environments based on a config option. The user wants to use the following code:

```php
try {
  do_something_that_might_raise();
} catch(\Exception $ex) {
  Rollbar::log(Log::ERROR, $ex);
}
```

And have it:

* report to Rollbar and swallow the exception in production,
* report to Rollbar and re-raise the exception in dev or test (to not have false positive tests)

### PR DESCRIPTION
**Pull request by ArturMoczulski**
Fixes #448 

Usage:

```php
$enviroment = "test";

Rollbar::init(array(
  "access_token" => $this->getTestAccessToken(),
  "environment" => $environment,
  "raise_on_error" => $environment == "test"
));

try {
  throw new \Exception();
} catch(\Exception $ex) {
  Rollbar::log(Level::ERROR, $ex);
}
```

Above configuration will cause the exception to be reraised only in the `test` environment

### CODE REVIEW

**Comment by ArturMoczulski** [comment]
This feature should also support passing a parameter to the `log` method to force ignoring reraising per individual calls

**Comment by waltjones** [comment]
LGTM

Side note: in the description example, `Rollbar::log` isn't using the `$ex` that's passed in. If this gets cut/pasted for a doc example, look out for that.

**Comment by ArturMoczulski** [comment]
Thanks for pointing that out @waltjones fixed it

**Comment by ArturMoczulski** [comment]
Once this is released, `raise_on_error` needs to get added to the doc

**Comment by ArturMoczulski** [comment]
Released in https://github.com/rollbar/rollbar-php/releases/tag/v1.8.0

**Pull request merged**
