### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by YamiChat**
INFO to info()
ERROR to error()

### CODE REVIEW

**Comment by rokob** [comment]
What is this? This is wrong, https://github.com/rollbar/rollbar-php/pull/199

**Comment by YamiChat** [comment]
I have something like this when used "INFO" :
_Constant 'INFO' not found in_
So I started to use as it is written in this manual
https://rollbar.com/docs/notifier/rollbar-php/
"info()"
and it works

**Comment by rokob** [comment]
The README@master are the docs for the tip of master, the README@v1.1.1 are the docs for the latest release, https://github.com/rollbar/rollbar-php/blob/v1.1.1/README.md

**Comment by YamiChat** [comment]
oh sorry

**Pull request closed without merging**
