### PR TITLE
Map missing PSR3 levels to supported levels

### PR DESCRIPTION
**Pull request by vdechenaux**
An alternative to https://github.com/rollbar/rollbar-php/pull/187

### CODE REVIEW

**Comment by ArturMoczulski** [comment]
This look great. I'm going to use this PR as base for for #140

**Comment by rokob** [comment]
Yeah this looks good to me too.

**Comment by vdechenaux** [comment]
Do you know when it will be released?

**Comment by ArturMoczulski** [comment]
@vdechenaux as soon as 1.2.0 is wrapped up, so probably next couple of days

**Pull request merged**
