### PR TITLE
Require the curl extension in composer.json

### PR DESCRIPTION
**Pull request by jenssegers**
I would also add a minimum PHP requirement.

### CODE REVIEW

**Comment by coryvirok** [comment]
Thanks for the PR @jenssegers. PHP isn't my primary language so can you help me understand the need and any potential downsides for this change?

Thanks!

**Comment by jenssegers** [comment]
This will warn users that try to install rollbar when they do not have the curl extension installed.

**Comment by jenssegers** [comment]
I did the same PR on Sentry's client: https://github.com/getsentry/raven-php/commit/6faf446d04c66809a4a08502eb2bd352c1620bff

**Comment by coryvirok** [comment]
Gotcha. Thanks for the info.

**Comment by brianr** [comment]
Thanks @jenssegers !

**Pull request merged**
