### PR TITLE
send pre/post code context for exceptions and errors

### PR DESCRIPTION
**Pull request by modethirteen**
Adds lines of code before and after the "code" line, as described in https://rollbar.com/docs/api/items_post/. We've been using this @MindTouch for a couple years with good results.

I didn't write a test as it uses file() to load source files into arrays. If you think a test is necessary I can create an abstraction for file() that is mockable.

### CODE REVIEW

**Comment by Crisfole** [comment]
Hey @modethirteen You're the man! This all looks really great.

If you don't *mind* writing a test we'd really appreciate it! I realize this involves refactoring the file reading a bit. Let me know if you need anything from us. We'd be happy to offer you any assistance you need.

**Comment by modethirteen** [comment]
@Crisfole no problem, i'll have the update shortly

**Comment by modethirteen** [comment]
@Crisfole updated and tests added

**Comment by Crisfole** [comment]
@modethirteen Nice! Thanks for that. I'll inspect later today, and get this merged in ASAP.

**Comment by modethirteen** [comment]
@Crisfole sounds great -- does a new tag get cut after that? it would be great it we were running the mainline releases.

**Comment by nocive** [comment]
@Crisfole any chance this will get merged soon?

**Comment by Crisfole** [comment]
@modethirteen @nocive I'd like to merge this soon. Tagging and releasing would need at least one extra set of eyes.

**Comment by Crisfole** [comment]
@brianr Take a peek? This looks good to me and it's tested.

**Comment by Crisfole** [comment]
Testing this locally right now and then I'll merge

**Comment by Crisfole** [comment]
Took a bunch longer because I discovered we didn't actually show the pre/post code yet, but had to make sure. This is fanstastic. Thank so much @modethirteen

**Pull request merged**
