### PR TITLE
support monolog ^3

### PR DESCRIPTION
**Pull request by jonnott**
## Description of the change

Support monolog 3 as well as 2.

## Type of change

- [x] New release

### CODE REVIEW

**Review by Vitaleks — APPROVED** [review]

**Review by Vitaleks — APPROVED** [review]
Well done

**Comment by danielmorell** [comment]
Hey, @jonnott. Thank you for this PR! Unfortunately, supporting monolog v3 is just a bit more work than adding it to our `composer.json` file.

It mostly impacts our verbose logging. I have finished updating the codebase and now just need to fix some brittle tests. I will have a PR tomorrow with the updates.

Also, we have an open issue for this #575.

**Comment by danielmorell** [comment]
On second thought. @jonnott do you mind if I push my commits to this branch and make them part of this PR?

**Comment by jonnott** [comment]
> On second thought. @jonnott do you mind if I push my commits to this branch and make them part of this PR?

Go ahead!

**Comment by danielmorell** [comment]
So, it turned out to be a bit of a massive change. Mostly, because of updates to the tests. Because, of that I put it in its own PR #602. Sorry for the back and forth on that!

**Comment by jonnott** [comment]
> So, it turned out to be a bit of a massive change. Mostly, because of updates to the tests. Because, of that I put it in its own PR #602. Sorry for the back and forth on that!

@danielmorell  Wow, that is a massive diff, thanks for your hard work. Sorry I'm not able to help more directly, as this is way above my experience level with monolog and Laravel logging internals.

I assume we'll need to wait for a monolog 3 compatible major release of rollbar/rollbar (v4?) before this can actually be used with Laravel 10.x though? (as 10.x doesn't support monolog 2)

**Comment by danielmorell** [comment]
> @danielmorell Wow, that is a massive diff, thanks for your hard work. Sorry I'm not able to help more directly, as this is way above my experience level with monolog and Laravel logging internals.
> 
> I assume we'll need to wait for a monolog 3-compatible release (v4?) and a new major version of rollbar-php-laravel before this can actually be used with Laravel 10.x though? (as 10.x doesn't support monolog 2)

The size of the diff is mostly from updating the tests.

We should be able to release a v8 beta of rollbar-php-laravel that uses the beta of rollbar-php v4. That would at least provide a way to do some early testing.

There is one more major fix that is needed before we release a stable version of v4, and that is a fix for #590.

**Comment by danielmorell** [comment]
Closing in favor of #602.

**Pull request closed without merging**
