### PR TITLE
 Don't ignore native PHP error handler

### PR DESCRIPTION
**Pull request by pavel-krulov**
Don't ignore native PHP error handler, when rollbar error handler setup.

### CODE REVIEW

**Comment by coryvirok** [comment]
Good catch, thanks. @ArturMoczulski can you take a look? We will also want to make sure there's a test for this case.

**Comment by rokob** [comment]
This looks good to me, this was part of the original set of changes moving from 0.18.2 to 1.0.0, c.f. https://github.com/rollbar/rollbar-php/commit/709fae9ee7f389b48e762ae8b5ac41b3cbbef635#diff-b156308dfc58bccc36efd0ce1cb4d496L68

The behaviour in 0.18.2 is the same as this PR, so for compatibility alone this is a good change.

**Comment by ArturMoczulski** [comment]
Let's merge this PR so I can start working on a test

**Comment by rokob** [comment]
👍

**Pull request merged**
