### PR TITLE
WIP - Adhere to PSR-*

### PR DESCRIPTION
**Pull request by Crisfole**
Adds check for coding standards.

### CODE REVIEW

**Comment by Crisfole** [comment]
Address #77 by complying with PEAR (which seems closest to our current code which doesn't use Namespaces).

This is a WIP: there are 88 non-fixable style errors; mostly missing comments and a bunch of class methods in `snake_case` (which should be `camelCase`).

**Comment by nocive** [comment]
@Crisfole PSR-* is probably what you wish to comply with, rather than PEAR (PEAR will be dead pretty soon anyway). :)

http://www.php-fig.org/psr/

**Comment by Crisfole** [comment]
@nocive thanks! Any chance there's a CodeSniffer config for it?

I wasn't thrilled with PSR's namespace rules in particular...it'd be a notable breaking change, and I'm not sure how to gracefully deprecate. It'd need to be a major version change (in which case there's more than one bit I'd like to improve).

**Comment by nocive** [comment]
adhering to PSR is the way to go moving forward imo, you don't necessarily need to comply with all PSR standards, but PSR-0 and 1 are usually followed by most php projects.
Sure there's a phpcs conf for it, here you go: http://cs.sensiolabs.org/

**Comment by Crisfole** [comment]
Gracias! Appreciate the link. 0 and 1 at least? Got it.

**Comment by nocive** [comment]
Sure, no worries, happy to help.
Feel free to mention me if you need more feedback.

**Comment by Crisfole** [comment]
I'll probably wind up doing this as a *giant* refactor which will definitely bump major version numbers...

**Comment by dlsteuer** [comment]
I'm going to close this pull request, the PSR standards are in the refactor1.0 branch

**Pull request closed without merging**
