### PR TITLE
Add missing transformer config option

### PR DESCRIPTION
**Pull request by danielroehrig**
This is needed to specify a transformer in Symfony. Otherwise, the transformer configuration option is not recognized and an error is thrown.

## Description of the change
Added "transformer" to the list of config options.

## Related issues
https://github.com/rollbar/rollbar-php-symfony-bundle/issues/65

### CODE REVIEW

**Comment by bxsx** [comment]
Hey @danielroehrig  and thanks for the PR 👌

I would like to merge it, but we need to make our CI happy first ;)
I'm afraid I don't have write access to the downstream, so can I have you replace tabs with spaces and add a trailing comma?

**Comment by danielroehrig** [comment]
Like this?

**Comment by bxsx** [comment]
Thanks @danielroehrig !

The branch appears to be out of sync with `master`. Could you merge branch `master` into your branch?

**Comment by danielroehrig** [comment]
I needed to have the change in an older branch. But I can also update the master branch.

**Comment by danielroehrig** [comment]
Added a new pull request directly for master. Use that and close this one.

**Comment by bxsx** [comment]
Thanks, @danielroehrig !

I close this PR as it's a duplicate of #543 now.

> I needed to have the change in an older branch. We are still on 2.1, But I can also update the master branch.

Both PRs seem to be based on the 3.0.0 version.

I'll merge #543 and backport it to the 1.x/2.x versions in separate PRs.

**Pull request closed without merging**
