### PR TITLE
WIP: Support psr/log 3

### PR DESCRIPTION
**Pull request by matt-h**
## Description of the change

> Please include a summary of the change and which issues are fixed.
> Please also include relevant motivation and context.

Update composer to support psr/log 3, most other packages support that now.

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers assigned
- [ ] Issue from task tracker has a link to this pull request
- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

**Comment by Lachie-Young** [comment]
Hey @matt-h,

Currently running into the same issue where I cannot install rollbar-php-laravel into the latest Laravel 9 project as it is using psr/log v3 which this package is not yet updated for.

Curious as to why this pull request was closed and/or if there's anything I can assist with to move this forward?

**Comment by danielmorell** [comment]
@Lachie-Young psr/log v3 would require a major version release since it requires the `void` return type on methods. You can read more about this here https://github.com/rollbar/rollbar-php-laravel/issues/128#issuecomment-1052377338.

To resolve your installation issue, try this...

```
composer require rollbar/rollbar --update-with-dependencies
```

**Comment by matt-h** [comment]
I closed the PR because I couldn't actually get it working and didn't want to spend more time on it. As danielmorell mentioned using the `--with-all-dependencies` flag allows you to use v2 which works just fine.

**Comment by Lachie-Young** [comment]
Thanks for your speedy replies @danielmorell @matt-h

**Pull request closed without merging**
