### PR TITLE
GitHub Issue #132: backwards compatibility with 0.18.2

### PR DESCRIPTION
**Pull request by ArturMoczulski**
Added the following methods to \Rollbar\Rollbar:

- report_message() - wrapper for log()
- report_exception() - wrapper for log()
- report_fatal_error() - wrapper for fatalHandler()
- report_php_error() - wrapper for errorHandler()
- flush() - empty method to not cause fatal errors in users' codebases

Added tests in tests/RollbarTest.php to check backward compatibility.

### CODE REVIEW

**Comment by ArturMoczulski** [comment]
All of the code climate issues I see are not really avoidable for this backward compatibility so I'm going to ignore those.

**Comment by ArturMoczulski** [comment]
This is ready for review

**Comment by rokob** [comment]
This looks good to me. Is this: "Avoid using static access to class '\Rollbar\Payload\Level'" something we should care about?

**Comment by rokob** [comment]
I looked into the static access warning, I think there might be something we could do to refactor the way levels are defined and used, but it is not important for what we are doing at the moment. So I am going to merge this.

**Pull request merged**
