### PR TITLE
Allow psr/log 2

### PR DESCRIPTION
**Pull request by Jean85**
## Description of the change
This PR allows the installation of `psr/log` 2.0 and 3.0. It's possible to support all of those versions at once since the interfaces are used but not implemented anywhere.
Backporting is unnecessary since both 2.0 and 3.0 require PHP 8.

This PR is also a blocker for Seldaek/monolog#1564

More details are available in the new meta document: https://www.php-fig.org/psr/psr-3/meta/

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development
- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by nicolas-grekas — DISMISSED** [review]
(a quick merge would be appreciate as that creates some DX issues with new Symfony projects)

**Comment by bxsx** [comment]
Hey @Jean85 and @nicolas-grekas.

It looks like our CI tests have failed. Does it work on your local machine?

**Comment by Jean85** [comment]
I made a mistake. The interface is used through the AbstractLogger, so you can't support 3.0 without adding the void return type to all the methods.
This would technically be a breaking change on your users, since they would have the same breakage you had in CI if they extended your classes without the void return types.

**Comment by bxsx** [comment]
Thanks for the clarification, @Jean85

In the current situation, I can merge the current PR (for 2.0) and put 3.0 request to our internal backlog so we can update the code in the next major release.

**Comment by Jean85** [comment]
Great! Thank you!

**Review by bxsx — APPROVED** [review]

**Pull request merged**
