### PR TITLE
Fix Error when handling invalid reponses from rollbar in php7.4.

### PR DESCRIPTION
**Pull request by lxlang**
Mitigating Array-style access of non-arrays in php 7.4

Prevents ErrorException: Trying to access array offset on value of type null.

### CODE REVIEW

**Comment by mrunalk** [comment]
@icsahn-rollbar, I can update the docs. Thanks @lxlang for adding the support for 7.3 and 7.4. We welcome contributions from the community.

**Comment by mrunalk** [comment]
@lxlang, we had to revert your change due to our travis builds not able to setup for 7.3 and 7.4 properly. But with #486 we have fixed the issue. Can you please test it and see if that solves your issue. Appreciate your feedback!

**Comment by fgilio** [comment]
@mrunalk so this needs to be merged again? I'm having this same issue https://github.com/rollbar/rollbar-php-laravel/issues/99 in with v6.0.0 and PHP 7.4

**Comment by lxlang** [comment]
@mrunalk 

Thanks for your patience. 

This change looks fine for me and I would really appreciate seeing this in a new release. 
Currently we have many problems with our rollbar integration because of this error.

**Comment by fgilio** [comment]
Meanwhile, we resorted to overloading the class in Composer to patch the issue. It's working fine 👍🏼

**Comment by lxlang** [comment]
That's great, but without a new release, I cannot utilize this change in my systems.

**Comment by fgilio** [comment]
> That's great, but without a new release, I cannot utilize this change in my systems.

@lxlang 👋🏼 it's now tagged here https://github.com/rollbar/rollbar-php/releases/tag/v2.1.0

Thanks for the fix

**Comment by mrunalk** [comment]
@lxlang @fgilio thank you for your patience. Yep it's now available as part of 2.1.0 release.

**Pull request merged**
